# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1opnW6F79BmK0KhToltUpqOEjfrjpYUzW
"""

import streamlit as st
import joblib
import numpy as np
import pandas as pd

# Model ve scaler yükle
model = joblib.load("logistic_model.pkl")
scaler = joblib.load("scaler.pkl")

st.title("Depresyon Riski Tahmin Sistemi")

# Kullanıcıdan giriş al
yas = st.number_input("Yaş", min_value=18, max_value=70, value=30)
cinsiyet = st.selectbox("Cinsiyet", options=["Erkek", "Kadın", "Diğer"])
uyku_suresi = st.slider("Uyku Süresi (Saat)", 0.0, 12.0, 6.5, 0.1)
egzersiz_sikligi = st.slider("Haftalık Egzersiz Sıklığı", 0, 14, 3)
ekran_suresi = st.slider("Günlük Ekran Süresi (Saat)", 0.0, 16.0, 6.0, 0.1)
istah = st.selectbox("İştah Seviyesi", options=["Az", "Normal", "Çok"])
stres = st.slider("Stres Seviyesi (1-10)", 1, 10, 5)
nabiz = st.number_input("Nabız (bpm)", min_value=40, max_value=120, value=70)
sigara = st.selectbox("Sigara Kullanımı", options=["Evet", "Hayır"])
alkol = st.selectbox("Alkol Tüketimi", options=["Hiç", "Az", "Orta", "Fazla"])

# Label encoding uyumu için mapping (aynı encoder'lar gibi)
cinsiyet_map = {"Erkek":0, "Kadın":1, "Diğer":2}
istah_map = {"Az":0, "Normal":1, "Çok":2}
sigara_map = {"Evet":1, "Hayır":0}
alkol_map = {"Hiç":0, "Az":1, "Orta":2, "Fazla":3}

# Veri hazırlama
input_data = np.array([[yas,
                        cinsiyet_map[cinsiyet],
                        uyku_suresi,
                        egzersiz_sikligi,
                        ekran_suresi,
                        istah_map[istah],
                        stres,
                        nabiz,
                        sigara_map[sigara],
                        alkol_map[alkol]]])

# Ölçekleme
input_scaled = scaler.transform(input_data)

if st.button("Tahmin Et"):
    pred = model.predict(input_scaled)[0]
    result = "Depresyon Riski VAR" if pred == 1 else "Depresyon Riski YOK"
    st.success(result)